version: '2.2'
services:
  telegram:
    build:
      context:  ./
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    extra_hosts:
      - "host.docker.internal:host-gateway"